Added new streamlit-extras `Jupyterlite`
arnaudmiribel/streamlit-extras pull request #192
Opened 2023-10-23 17:16 UTC by Rjchauhan18

I have added new streamlit extra -> `jupyterlite` as per https://github.com/arnaudmiribel/streamlit-extras/issues/133

Hello @arnaudmiribel 

For testing I have tryed to follow the step according to this [contribution guidelines](https://arnaudmiribel.github.io/streamlit-extras/contributing/) but my gallery/streamlit_app.py keeps running ... . 

So, can you please review it ? but i am sure that code is fine.

2023-11-02 03:23 UTC, Rjchauhan18 commented
Hello @arnaudmiribel 
Can you please review it?

2023-11-02 12:25 UTC, arnaudmiribel commented on src/streamlit_extras/jupyterlite/__init__.py
> +__desc__ = "Add jupiterlite to your Streamlit app in one command"  # description of your extra!
```suggestion
__desc__ = "Add a Jupyterlite sandbox to your Streamlit app in one command" 
```

2023-11-02 12:26 UTC, arnaudmiribel commented on src/streamlit_extras/jupyterlite/__init__.py
> +__experimental_playground__ = False  # Optional
```suggestion
__title__ = "Jupyterlite"
__desc__ = "Add a Jupyterlite sandbox to your Streamlit app in one command" 
__icon__ = "💡"
__examples__ = [example]
__author__ = "Rahul Chauhan"
__experimental_playground__ = False
```

2023-11-02 12:29 UTC, arnaudmiribel requested changes
Thanks for the contribution! Please add a docstring and apply proper linting (using pre-commit) to your file, and that should do.

2023-11-02 12:29 UTC, arnaudmiribel commented on src/streamlit_extras/jupyterlite/__init__.py
> +def jupyterlite(height:int,width:int):
Please add a docstring to this function. Look at other extras for inspiration and layout! Thanks ☺️

2023-11-02 21:19 UTC, arnaudmiribel reviewed
Nice job on passing the linting tests! Only remaining thing is please add a docstring to `jupyterlite` :-) you can look at other extras to get inspired. We use the Google docstring style. Example:

```python
@extra
def style_metric_cards(
    background_color: str = "#FFF",
    border_size_px: int = 1,
    border_color: str = "#CCC",
    border_radius_px: int = 5,
    border_left_color: str = "#9AD8E1",
    box_shadow: bool = True,
) -> None:
    """
    Applies a custom style to st.metrics in the page

    Args:
        background_color (str, optional): Background color. Defaults to "#FFF".
        border_size_px (int, optional): Border size in pixels. Defaults to 1.
        border_color (str, optional): Border color. Defaults to "#CCC".
        border_radius_px (int, optional): Border radius in pixels. Defaults to 5.
        border_left_color (str, optional): Borfer left color. Defaults to "#9AD8E1".
        box_shadow (bool, optional): Whether a box shadow is applied. Defaults to True.
    """
```

So here would be something like:

```python
@extra
def jupyterlite(height: int, width: int):
    """
    Add a Jupyterlite sandbox to your Streamlit app
    
    Args:
        width (int): Width of the Jupyterlite sandbox
        height (int): Height of the Jupyterlite sandbox
    """

    iframe(
        src="https://jupyterlite.github.io/demo/repl/index.html?kernel=python&toolbar=1",
        height=height,
        width=width,
    )
```

2023-11-03 13:22 UTC, arnaudmiribel approved these changes

2023-11-03 13:23 UTC, merged