Added a new extra, st-card. A Streamlit UI Card component
arnaudmiribel/streamlit-extras pull request #87
Opened 2022-11-21 15:32 UTC by gamcoh

Hey @arnaudmiribel , just added a new extra which is a nice UI Card with an image in the background and a title + description centered in the foreground

2022-11-22 23:28 UTC, arnaudmiribel commented
Hey @gamcoh, looks like a lovely addition! Thanks a lot for your contribution.

Would you mind updating this PR to:
- merge from main
- reflect changes made in [this PR](https://github.com/gamcoh/st-card/pull/2) into the definition of your extra here? essentially updating st-card version and also the `example()` function

2022-11-22 23:31 UTC, arnaudmiribel requested changes

2022-11-22 23:31 UTC, arnaudmiribel commented on src/streamlit_extras/card/__init__.py
> +    )
This could use the latest st-card API which uses `url="https://github.com/gamcoh/st-card",` too

2022-11-22 23:31 UTC, arnaudmiribel commented on src/streamlit_extras/card/__init__.py
> +__title__ = "Streamlit Card"  # title of your extra!
```suggestion
__title__ = "Card"  # title of your extra!
```

(otherwise we get "Streamlit" written likely everywhere)

2022-11-22 23:31 UTC, arnaudmiribel commented on src/streamlit_extras/card/__init__.py
> +__icon__ = "🖼️"  # give your extra an icon!
```suggestion
__icon__ = "💳"  # give your extra an icon!
```

If you don't mind, that 🖼️ is taken for the upcoming [Chart container extra](https://github.com/arnaudmiribel/streamlit-extras/pull/80) so suggested another one 💳 (feel free to use another). I know, some day will come where emojis will inevitably collide given the amount of extras we get.. but until then...

2022-11-22 23:31 UTC, arnaudmiribel commented on pyproject.toml
> +streamlit-card = ">=0.0.3"
Mind upgrading that to latest?

2022-11-22 23:33 UTC, arnaudmiribel commented
Thanks a lot for your contribution @gamcoh! This is a great addition. I left a quick review, I think that solving it + merging from main should work perfectly. Let me know if you encounter problems!

2022-11-23 10:34 UTC, gamcoh commented
Hey @arnaudmiribel, thanks for the review, should be good now, but the merge is blocked

2022-11-23 16:32 UTC, arnaudmiribel commented on src/streamlit_extras/card/__init__.py
> +__github_repo__ = "gamcoh/st-card" # Optional
```suggestion
__github_repo__ = "gamcoh/st-card"  # Optional

```

2022-11-23 16:36 UTC, arnaudmiribel commented on src/streamlit_extras/card/__init__.py
> +__github_repo__ = "gamcoh/st-card"  # Optional
```suggestion
__github_repo__ = "gamcoh/st-card"  # Optional repo handle

```

2022-11-23 16:51 UTC, arnaudmiribel approved these changes

2022-11-23 16:52 UTC, merged